### PR TITLE
Updated Go Redis to 7th version, error and testify update.

### PR DESCRIPTION
**Pull request by renta**
Updated [go-redis](https://github.com/go-redis/redis) to version 7 (current stable version). Also updated   [errors](github.com/pkg/errors) and [testify](github.com/stretchr/testify). This update was needed because if project uses Redis client itself (v7) then it will be v6 (of current Redisqueue) and v7 simultaneously.

### CODE REVIEW

**Comment by theckman** [comment]
This would be a :-1: from me as it would make this package no longer work for `dep` users.

**Comment by robinjoseph08** [comment]
@theckman Since Go modules is considered [production-ready](https://github.com/golang/go/wiki/Modules) in Go 1.14, I'm inclined to migrate this project fully over to modules so that it's able to get updates for its dependencies (like `go-redis`). The last version created that supports dependency management through anything other than Go modules will v1.1.0.

@renta Apologies for the long delay in addressing this PR. It looks like `v8` has been released in the past 2 months. I also want to make a few other changes to the README to indicate this as well, so I'll just copy your changes into another PR and merge it from there. Thank you for your contribution!

**Comment by robinjoseph08** [comment]
Err scratch that, it doesn't look like `v8` is released yet, so I'll also just be updating to `v7`.

**Comment by robinjoseph08** [comment]
I've updated it and created v2.0.0 that uses `github.com/go-redis/redis/v7`.

**Pull request closed without merging**
